//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRACTIKA5
{
    using System;
    using System.Collections.Generic;
    
    public partial class employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employees()
        {
            this.order_details = new HashSet<order_details>();
        }
    
        public int ID_employee { get; set; }
        public string firstname { get; set; }
        public string surname { get; set; }
        public string midlename { get; set; }
        public string phone_number { get; set; }
        public string logins { get; set; }
        public string passwords { get; set; }
        public int specialization_ID { get; set; }
        public Nullable<int> departament_ID { get; set; }
        public Nullable<int> order_ID { get; set; }
    
        public virtual departaments departaments { get; set; }
        public virtual orders orders { get; set; }
        public virtual specializations specializations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_details> order_details { get; set; }
    }
}
