//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRACTIKA5
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_details
    {
        public int ID_order_detail { get; set; }
        public Nullable<int> order_ID { get; set; }
        public Nullable<int> product_ID { get; set; }
        public Nullable<int> employee_ID { get; set; }
    
        public virtual employees employees { get; set; }
        public virtual orders orders { get; set; }
        public virtual products products { get; set; }
    }
}
