//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRACTIKA5
{
    using System;
    using System.Collections.Generic;
    
    public partial class warehouse
    {
        public int ID_warehouse { get; set; }
        public int quantity { get; set; }
        public Nullable<int> product_ID { get; set; }
        public Nullable<int> supplier_ID { get; set; }
    
        public virtual products products { get; set; }
        public virtual suppliers suppliers { get; set; }
    }
}
